server:
  port: 8002

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lsyyunn/spring-cloud-config-repo/
          username: 2540400974@qq.com
          password: Abc377544
          search-paths: config-repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka