server:
  port: 9000
spring:
  application:
    name: eureka-serve
#注册中心配置
eureka:
  instance:
    hostname: localhost
  client:
    #获取注册中心服务的列表
    fetch-registry: false
    #是否向Eureka服务器注册其信息以供其它Eureka客户端发现
    register-with-eureka: false
    #  注册中心地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    #注册中心清除不在线 微服务时间间隔60秒

#    eureka-service-url-poll-interval-seconds: